### PR TITLE
Help with incremental conversion to OCaml values

### PR DESCRIPTION
**Pull request by g2p**

### CODE REVIEW

**Comment by tizoc** [comment]
The `Clone` fix was already done in #17. What is the use case of the `impl<'a, A> ToOCaml<A> for OCaml<'a, A>`?

**Comment by g2p** [comment]
It's useful for converting containers while using something other than the normal ToOCaml implementation on every element; see this test: https://github.com/g2p/ocaml-interop/blob/ocamlbox/testing/rust-caller/src/lib.rs#L274

**Comment by tizoc** [comment]
@g2p oh I see. That makes total sense. Will come back to this once #17 is merged.

**Comment by tizoc** [comment]
Can you rebase this on top of the current master? The Clone/Copy stuff is not required anymore.

Also, note that on the new ocaml-interop `OCamlAllocResult` doesn't exist anymore, `OCaml<T>` values are now returned directly.

**Comment by g2p** [comment]
I'll drop this one (it didn't work well with the new lifetimes on ToOCaml, as I recall);
there's a commit in #24 that exposes cons and that works just as well.

**Pull request closed without merging**
