### PR TITLE
OCaml Runtime lock instead of GC handle

### PR DESCRIPTION
**Pull request by tizoc**
Replace use of a GC handle with an OCaml Runtime handle that has to be passed around trough mutable borrows.

- [x] Replace GC handle with runtime handle that has to be passed around
- [x] Support for blocking sections through the use of the OCaml Runtime handle
- [x] Update all documentation and examples
- [x] Tests for parallelism between Rust and OCaml code when using blocking sections
- [x] more `compile_fail` tests
- [x] Update CHANGELOG

## Summary of current changes

1) The GC-handle has been replaced by an OCaml-Runtime-handle that must be passed around as a `&mut` reference. `OCaml<'a, T>` values have their lifetime associated to this handle through an immutable borrow, just like it used to be with the now-gone GC-handle.
2) Exported functions don't implicitly open an `ocaml_frame!` anymore, but instead receive an OCaml-runtime-handle:

```rust
ocaml_export! {
    // In the expanded code, any OCaml<T> parameters are built with their lifetimes associated
    // to `cr` (a `&mut OCamlRuntime`).
    fn rust_twice_boxed_i64(cr, num: OCaml<OCamlInt64>) -> OCaml<OCamlInt64> {
        let num: i64 = num.to_rust();
        let result = num * 2;
        ocaml_alloc!(result.to_ocaml(cr))
    }
}
```

expands into:

```rust
#[no_mangle]
pub extern "C" fn rust_twice_boxed_i64(
    num: ::ocaml_interop::RawOCaml,
) -> ::ocaml_interop::RawOCaml {
    let cr = unsafe { &mut ::ocaml_interop::OCamlRuntime::recover_handle() };
    let num: OCaml<OCamlInt64> = unsafe { ::ocaml_interop::OCaml::new(cr, num) };
    {
        let retval: OCaml<OCamlInt64> = {
            let num: i64 = num.to_rust();
            let result = num * 2;
            {
                let res = result.to_ocaml(unsafe { cr.token() });
                res.mark(cr).eval(cr)
            }
        };
        unsafe { retval.raw() }
    }
}
```

3) `ocaml_frame!` doesn't create a GC-handle anymore, but instead takes as input an OCaml-Runtime-handle, and uses it to instantiate a new frame and list of Root-variables through an immutable borrow.
4) `ocaml_frame!` is now only required to instantiate Root-variables, any interaction with the OCaml runtime will make use of an OCaml-Runtime-handle, which should be around already. The syntax also changed slightly, requiring a comma after the OCaml-Runtime-handle parameter.

```rust
// old
ocaml_frame!(gc(r1, r2, /* ... */), {
    // ...
})

// new
// cr: &mut OCamlRuntime, but used as &OCamlRuntime by ocaml_frame!.
ocaml_frame!(cr, (r1, r2, /* ... */), {
    // ...
})
```

5) `OCamlAllocToken` can now be used to (unsafely) recover the runtime handle. This used internally as a workaround to Rust's borrow checker not allowing a function to receive a mutably borrowed parameter along with immutable borrows associated to it:

```rust
// cr: &mut OCamlRuntime
let result = ocaml_alloc!(alloc_function(cr, &unrooted_ocaml_value1, &unrooted_ocaml_value2));
// expands into:
let result = alloc_function(unsafe { cr.token() }, &unrooted_ocaml_value1, &unrooted_ocaml_value2)).mark(cr).eval(cr);
```

Here `mark(cr)` takes a `&mut OCamlRuntime` to invalidate older `OCaml<'a, T>` values and `eval(cr)` an `&OCamlRuntime` to produce an `OCaml<'a, T>` result.

Inside `alloc_function`, the token can be used to recover the runtime handle to open a new `ocaml_frame!` or call other functions that require an `&mut OCamlRuntime`:

```rust
fn alloc_function(
    token: OCamlAllocToken,
    unrooted_ocaml_value1: &OCaml<T>,
    unrooted_ocaml_value2: &OCaml<U>,
) -> OCamlAllocResult<V> {
    let cr = unsafe { &mut token.recover_runtime_handle() }; // `token` is consumed here
    // TODO: a way to re-validate OCaml<T> arguments, and probably an annotation to handle that
    // and the recovery of the runtime handle automatically and safely.
    // Maybe something like:
    let unrooted_ocaml_value1 = unrooted_ocaml_value1.refresh(cr);
    let unrooted_ocaml_value2 = unrooted_ocaml_value2.refresh(cr);
    // ...
}
```

An annotated version would look somewhat like:

```rust
#[ocaml_alloc]
fn alloc_function<'a>(
    cr: &'a mut OCamlRuntime,
    unrooted_ocaml_value1: &OCaml<'a, T>,
    unrooted_ocaml_value2: &OCaml<'a, U>,
) -> OCamlAllocResult<V> {
    // ...
}
```

6) `OCamlRuntime::releasing_runtime(&mut self, f: FnOnce() -> T)` releases the OCaml runtime, calls `f`, and then re-acquires the OCaml runtime. Maybe more complicated patterns should be supported, but for now I haven't given this much thought.

7) ~Except for immediate values like fixnums, unit and booleans, `OCaml<'a, T>` isn't marked as `Copy` anymore, and `&OCaml<'a, T>` values are used now in most places. The idea here is to leave some space for an API that can mutably expose internal OCaml values data to Rust.~ (reverted after some discussion)

8) `OCamlRef` has been renamed to `OCamlRooted`.

9) Rust functions that are exported to OCaml must now declare at least one argument.

### CODE REVIEW

**Comment by tizoc** [comment]
@zshipko here is the WIP of the API changes. The main change is that now `ocaml_frame!` is only needed when new root variables are required for rooting values. The GC handle is gone, and has been replaced by an OCaml Runtime handle that has to be passed around. For ocaml-derive things should be almost the same, the main difference is that it should obtain the runtime handle through `let cr = unsafe { ocaml_interop::OCamlRuntime::acquire() };` at the beginning of the function. Then the `Value` arguments should be converted into `OCaml<'a, T>` values using `cr` in the same way `ocaml-interop` does it in the `ocaml_export!` macro:

```rust
// `string_arg` is `Value`/`RawOCaml` although it was declared
// as `OCaml<String>` in the function signature.
// Here it is converted to an actual `OCaml<String>` with a lifetime associated to
// the obtained OCaml Runtime handle.
let string_arg : OCaml<String> = unsafe { ocaml_interop::OCaml::new(cr, string_arg) };
```

There is still quite a bunch of stuff I have to do here (the change from the GC handle to a runtime handle in itself wasn't that big, but it was at the core of the whole thing and affected everything else), but I this aspect in particular is very unlikely to change.

Once I'm done with the remaining docs/example updates I will try to finish with the ocaml runtime lock thing (to allow for Rust and OCaml code to run in parallel).

**Comment by tizoc** [comment]
Btw, eventually I would like to push the runtime lock + lifetimes stuff downstream into ocaml-sys, but that is for the future, once all these changes have been stabilized.

**Comment by zshipko** [comment]
Awesome, this looks like it will be really nice!

I will work on updating the derive macros to match your new interface - I had paused that work waiting to see what these changes would look like.

Moving this stuff into ocaml-sys at some point sounds good too.

**Comment by tizoc** [comment]
I will be merging this one (along with the polymorphic variants PR) soon to make a new release. There are probably still things to improve, but I think it is good enough for now.

**Comment by zshipko** [comment]
Great! I will go through these changes to get a better idea of what's new. I have been busy with other work but will be able to get back to updating ocaml-derive next week most likely.

**Comment by tizoc** [comment]
@zshipko while there are many changes, API-wise things should be mostly the same for ocaml-derive, other stuff is about better expressing what is happening in terms of ownership, and for supporting parallelism between Rust and OCaml code. Then on another PR I have added support for polymorphic variants (converting from OCaml to Rust for now, but will work on supporting Rust->OCaml after I'm done with other stuff), which at some point should require an ocaml-derive equivalent, just not sure yet about how it would look.

When you start working on it ping me if you want to discuss anything about the ocaml-derive API or want help with anything

**Pull request merged**
